ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.prosenjith.messos.ApplicationKt.module

database:
  url: "jdbc:postgresql://localhost:5432/messos_db"
  driver: "org.postgresql.Driver"
  username: "messos"
  password: "messos_dev"
  pool:
    maximumPoolSize: 10
    minimumIdle: 2

jwt:
  secret: "dev-secret-change-in-production-min-32-chars!!"
  issuer: "messos-api"
  audience: "messos-app"
  expiryDays: 30
